// src/context/LanguageContext.jsx
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brand_name: 'Costa Gym',
    brand_subtitle: 'Your other home',
    
    // Navbar
    nav_home: 'Home',
    nav_membership: 'Membership',
    nav_about: 'About',
    nav_offers: 'Offers',
    nav_gallery: 'Gallery',
    nav_success: 'Success Stories',
    nav_contact: 'Contact',
    nav_join_now: 'Join Now',

    // Hero Section
    hero_premier: "Egypt's Premier Gym",
    hero_forge_legacy: 'FORGE YOUR LEGACY HERE.',
    hero_subtitle: 'World-class equipment. Expert trainers. A community that pushes you further. Your transformation starts the moment you walk through our doors.',
    hero_join_now: 'Join Now',
    hero_whatsapp: 'WhatsApp Us',
    hero_view_offers: 'View Offers',
    stat_active_members: 'Active Members',
    stat_expert_trainers: 'Expert Trainers',
    stat_equipment_pieces: 'Equipment Pieces',
    stat_years_excellence: 'Years of Excellence',

    // Why Choose Us
    why_accent: 'Why Costa?',
    why_title: 'THE COSTA DIFFERENCE',
    why_subtitle: "We don't just offer a gym. We offer a complete transformation ecosystem.",
    feature_equip_title: 'World-Class Equipment',
    feature_equip_desc: 'Over 200 premium machines and free weights from leading manufacturers.',
    feature_trainers_title: 'Expert Trainers',
    feature_trainers_desc: 'Certified professionals dedicated to your transformation and success.',
    feature_programs_title: 'Diverse Programs',
    feature_programs_desc: 'From strength training to cardio, HIIT to yoga — we have it all.',
    feature_results_title: 'Proven Results',
    feature_results_desc: 'Thousands of success stories. Real transformations. Real people.',

    // Membership Section
    plans_accent: 'Flexible Plans',
    plans_title: 'MEMBERSHIP PLANS',
    plans_subtitle: 'No hidden fees. No contracts. Just results.',
    plans_view_all: 'View All Plans',
    plans_currency: 'EGP',
    plans_best_value: 'BEST VALUE',
    plans_popular: 'POPULAR',
    plans_month: 'month',
    plans_months: 'months',
    plans_year: 'year',
    plans_get_started: 'Get Started',
    plans_most_popular: 'Most Popular',
    plans_commit: 'Commit Now',
    plans_annual: 'Go Annual',

    // Features Checklist
    feat_gym_access: 'Full gym access',
    feat_locker_shower: 'Locker & shower access',
    feat_basic_assessment: 'Basic fitness assessment',
    feat_app_access: 'App access',
    feat_classes_5: 'Group classes (5/week)',
    feat_classes_unlimited: 'Unlimited group classes',
    feat_full_assessment: 'Full fitness assessment',
    feat_pt_1: '1 PT session / month',
    feat_pt_2: '2 PT sessions / month',
    feat_pt_4: '4 PT sessions / month',
    feat_nutrition_consult: 'Nutrition consultation',
    feat_nutrition_plan: 'Nutrition plan included',
    feat_nutrition_custom: 'Custom nutrition plan',
    feat_guest_2: 'Guest passes (2/month)',
    feat_guest_unlimited: 'Unlimited guest passes',
    feat_priority_booking: 'Priority class booking',
    feat_priority_all: 'Priority everything',
    feat_assigned_locker: 'Premium locker assigned',
    feat_quarterly_assessment: 'Quarterly assessments',
    feat_merchandise: 'Free Costa merchandise',

    // Testimonials
    test_accent: 'Real Results',
    test_title: 'MEMBER STORIES',
    test_subtitle: 'Hear from the people who transformed their lives with Costa.',
    test_more: 'More Success Stories',
    test_name_ahmed: 'Ahmed Hassan',
    test_role_ahmed: 'Lost 30kg in 6 months',
    test_text_ahmed: 'Costa Gym changed my life completely. The trainers here push you to be your best version.',
    test_name_sara: 'Sara Mohamed',
    test_role_sara: 'Competed nationally',
    test_text_sara: 'I went from never lifting to competing in nationals. The coaching here is second to none.',
    test_name_khaled: 'Khaled Ibrahim',
    test_role_khaled: 'Gained 15kg muscle',
    test_text_khaled: 'The programming, nutrition advice, and community here is unmatched in Egypt.',

    // CTA Banner
    cta_ready: 'Ready To Begin?',
    cta_start: 'START YOUR TRANSFORMATION TODAY',
    cta_subtitle: 'Your goals are waiting. Your best self is waiting. Stop waiting and start.',
    cta_join: 'Join Now',
    cta_contact: 'Contact Us',

    // Footer
    footer_desc: "Your other home. Premium fitness experience in Egypt. Transform your body, dominate your limits, excel in life.",
    footer_quick_links: 'Quick Links',
    footer_contact: 'Contact Us',
    footer_hours: 'Working Hours',
    footer_open_365: 'Open 365 Days a Year',
    footer_admin: 'Admin Portal',
    footer_copyright: 'Costa Gym. All Rights Reserved.',

    // Membership Page
    mem_accent: 'Flexible Options',
    mem_title: 'MEMBERSHIP PLANS',
    mem_subtitle: 'Choose the plan that fits your goals. Every plan includes full access to our world-class facilities.',
    mem_include_title: 'All Plans Include',
    mem_inc_1: 'Free locker & shower access',
    mem_inc_2: 'Parking for members',
    mem_inc_3: 'Air-conditioned facility',
    mem_inc_4: 'Hygienic equipment (sanitized daily)',
    mem_inc_5: 'WiFi throughout the gym',
    mem_inc_6: 'Dedicated changing rooms',
    mem_inc_7: 'No joining fee for annual plans',
    mem_inc_8: 'Cancel anytime (terms apply)',

    // About Page
    ab_accent: 'Our Story',
    ab_title: 'ABOUT COSTA GYM',
    ab_est: 'Est. 2014',
    ab_story_title: 'OUR STORY',
    ab_story_p1: 'Costa Gym was born from a simple but powerful belief: every person deserves access to world-class training. Founded in 2014 by former national athlete Ahmad El-Sayed, Costa started as a 500 sqm facility with 30 members.',
    ab_story_p2: 'Today, we operate a 3,000 sqm state-of-the-art facility, serve over 5,000 active members, and have helped thousands achieve transformations they once thought impossible.',
    ab_story_p3: 'Our philosophy is simple: Excellence in everything. From our equipment to our coaching, from our nutrition guidance to our community culture — we settle for nothing less than the best.',
    ab_years_operating: 'Years Operating',
    ab_active_members: 'Active Members',
    ab_certified_trainers: 'Certified Trainers',
    ab_equipment_pieces: 'Equipment Pieces',
    ab_sqm_facility: 'Sqm Facility',
    ab_weekly_classes: 'Weekly Classes',
    ab_facilities_accent: 'World Class',
    ab_facilities_title: 'FACILITIES',
    ab_facilities_subtitle: 'Everything you need to train, recover, and excel.',
    ab_facility_weights: 'Free Weights Zone',
    ab_facility_weights_desc: 'Dumbbells up to 100kg, barbells, and full squat rack area.',
    ab_facility_cardio: 'Cardio Floor',
    ab_facility_cardio_desc: 'Treadmills, bikes, rowers, stair climbers — all premium brands.',
    ab_facility_classes: 'Group Classes Studio',
    ab_facility_classes_desc: 'HIIT, spinning, Zumba, Pilates — 30+ classes per week.',
    ab_facility_func: 'Functional Training',
    ab_facility_func_desc: 'Cables, TRX, battle ropes, sleds, and more.',
    ab_facility_lockers: 'Premium Locker Rooms',
    ab_facility_lockers_desc: 'Clean, spacious changing rooms with hot showers.',
    ab_facility_parking: 'Free Parking',
    ab_facility_parking_desc: 'Dedicated member parking available all hours.',
    ab_facility_wifi: 'High-Speed WiFi',
    ab_facility_wifi_desc: 'Stay connected throughout the entire facility.',
    ab_facility_recovery: 'Recovery Zone',
    ab_facility_recovery_desc: 'Ice bath, sauna, and massage therapy available.',
    ab_team_accent: 'The Team',
    ab_trainers_title: 'MEET OUR TRAINERS',
    ab_trainers_subtitle: 'Industry-certified experts who live and breathe fitness.',
    ab_trainer_mustafa: 'Coach Mustafa',
    ab_trainer_mustafa_spec: 'Strength & Powerlifting',
    ab_trainer_rana: 'Coach Rana',
    ab_trainer_rana_spec: 'Body Transformation',
    ab_trainer_tarek: 'Coach Tarek',
    ab_trainer_tarek_spec: 'Athletic Performance',
    ab_trainer_nadia: 'Coach Nadia',
    ab_trainer_nadia_spec: 'Yoga & Flexibility',
    ab_experience: 'experience',
    ab_years: 'years',

    // Contact Page
    con_accent: 'Get In Touch',
    con_title: 'CONTACT US',
    con_name_label: 'Full Name *',
    con_email_label: 'Email Address *',
    con_phone_label: 'Phone Number *',
    con_message_label: 'Message *',
    con_name_place: 'Your full name',
    con_email_place: 'Your email address',
    con_phone_place: '+20 1XX XXX XXXX',
    con_message_place: 'How can we help you?',
    con_send: 'Send Message',
    con_sending: 'Sending...',
    con_info_title: 'Contact Information',
    con_info_desc: "Have questions? We'd love to hear from you. Drop by or shoot us a message.",
    con_location_title: 'Location',
    con_hours_title: 'Opening Hours',
    con_follow_title: 'Follow Us',

    // Offers Page
    off_accent: 'Exclusive',
    off_title: 'ACTIVE OFFERS',
    off_subtitle: 'Take advantage of our limited-time promotions and kickstart your journey.',
    off_claim: 'Claim Offer',
    off_expired: 'Expired',
    off_ends: 'Ends',
    off_comp_title: 'ACTIVE COMPETITIONS',
    off_comp_subtitle: 'Challenge yourself, compete with others, and win amazing prizes.',
    off_comp_join: 'Enter Competition',
    off_comp_joined: 'Already Entered',
    off_comp_ends: 'Ends in',
    off_comp_prize: 'Prize',

    // Success Stories Page
    succ_accent: 'Transformation',
    succ_title: 'SUCCESS STORIES',
    succ_subtitle: 'Real members. Real dedication. Real, life-changing results.',
    succ_before: 'Before',
    succ_after: 'After',
    succ_lost: 'Lost',
    succ_gained: 'Gained',
    succ_in: 'in',
    succ_months: 'months',
    succ_read_more: 'Read Full Story',

    // Gallery Page
    gal_accent: 'Inside Costa',
    gal_title: 'PHOTO GALLERY',
    gal_subtitle: 'Take a virtual tour of our premium training facilities and equipment.',
    gal_all: 'All',
    gal_weights: 'Weights',
    gal_cardio: 'Cardio',
    gal_studio: 'Studio',
    gal_recovery: 'Recovery',

    // Admin Sidebar Layout
    admin_title: 'Admin Dashboard',
    admin_nav_dashboard: 'Dashboard',
    admin_nav_offers: 'Offers',
    admin_nav_competitions: 'Competitions',
    admin_nav_entries: 'Competition Entries',
    admin_nav_trials: 'Trial Registrations',
    admin_nav_memberships: 'Membership Registrations',
    admin_logout: 'Logout',
    admin_panel_subtitle: 'Admin Panel',

    // Admin Login Page
    admin_login_title: 'Admin Login',
    admin_login_email: 'Email Address',
    admin_login_password: 'Password',
    admin_login_button: 'Sign In',
    admin_login_signing_in: 'Signing In...',
    admin_login_unauthorized: 'Protected area. Unauthorized access is prohibited.',

    // DataTable
    admin_table_search: 'Search...',
    admin_table_export: 'Export CSV',
    admin_table_loading: 'Loading records...',
    admin_table_action: 'Action',
    admin_table_showing: 'Showing',
    admin_table_of: 'of',
    admin_table_records: 'records',

    // Admin Dashboard
    admin_db_overview: "Overview of your gym's activity",
    admin_db_recent_trials: 'Recent Trial Registrations',
    admin_db_recent_entries: 'Recent Competition Entries',
    admin_db_recent_memberships: 'Recent Membership Registrations',
    admin_db_view_all: 'View All',
    admin_db_no_reg: 'No registrations yet.',
    admin_db_no_entries: 'No competition entries yet.',
    admin_db_no_memberships: 'No memberships registered yet.',

    // Admin Offers
    admin_offers_manage: 'Manage Offers',
    admin_offers_total: 'total offers',
    admin_offers_new: 'New Offer',
    admin_offers_no: 'No offers yet. Create your first one!',
    admin_offers_col_title: 'Title',
    admin_offers_col_desc: 'Description',
    admin_offers_col_end: 'End Date',
    admin_offers_col_status: 'Status',
    admin_offers_active: 'Active',
    admin_offers_off: 'Off',
    admin_offers_edit: 'Edit Offer',
    admin_offers_create: 'Create New Offer',
    admin_offers_form_title: 'Title *',
    admin_offers_form_desc: 'Description *',
    admin_offers_form_end: 'End Date',
    admin_offers_form_active: 'Active (visible on site)',
    admin_offers_save: 'Create Offer',
    admin_offers_update: 'Update Offer',
    admin_offers_saving: 'Saving...',
    admin_offers_cancel: 'Cancel',
    admin_offers_confirm_delete: 'Delete this offer?',

    // Admin Competitions
    admin_comps_manage: 'Manage Competitions',
    admin_comps_total: 'total competitions',
    admin_comps_new: 'New Competition',
    admin_comps_no: 'No competitions yet.',
    admin_comps_prize: 'Prize',
    admin_comps_ends: 'Ends',
    admin_comps_pick_winner: 'Pick Winner',
    admin_comps_edit: 'Edit Competition',
    admin_comps_create: 'Create Competition',
    admin_comps_form_title: 'Title *',
    admin_comps_form_desc: 'Description *',
    admin_comps_form_prize: 'Prize *',
    admin_comps_form_end: 'End Date',
    admin_comps_form_active: 'Active (visible on site)',
    admin_comps_save: 'Create',
    admin_comps_update: 'Update',
    admin_comps_confirm_delete: 'Delete this competition and all its entries?',
    admin_comps_winner_title: 'Random Winner Generator',
    admin_comps_winner_pick: 'Pick Random Winner',
    admin_comps_winner_selecting: 'Selecting Winner...',
    admin_comps_winner_text: 'Click the button to randomly select a winner from all registered participants.',
    admin_comps_winner_success: 'Winner Selected!',
    admin_comps_winner_saved: 'Winner saved to database ✓',
    admin_comps_winner_no_entries: 'No entries for this competition.',
    admin_comps_winner_close: 'Close',

    // Admin Trial Registrations
    admin_trials_manage: 'Trial Registrations',
    admin_trials_total: 'total registrations',
    admin_trials_empty: 'No trial registrations yet.',
    admin_trials_col_name: 'Full Name',
    admin_trials_col_phone: 'Phone',
    admin_trials_col_age: 'Age',
    admin_trials_col_goal: 'Goal',
    admin_trials_col_registered: 'Registered',
    admin_trials_confirm_delete: 'Delete this registration?',

    // Admin Competition Entries
    admin_entries_manage: 'Competition Entries',
    admin_entries_total: 'total entries',
    admin_entries_empty: 'No competition entries yet.',
    admin_entries_col_name: 'Full Name',
    admin_entries_col_phone: 'Phone',
    admin_entries_col_comp: 'Competition',
    admin_entries_col_registered: 'Registered',
    admin_entries_confirm_delete: 'Remove this competition entry?',

    // Membership Registration Form & Admin Membership
    mem_reg_title: 'Membership Registration',
    mem_reg_subtitle: 'Register for your selected plan',
    mem_reg_plan: 'Selected Plan',
    mem_reg_price: 'Price',
    mem_reg_submit: 'Register Now',
    mem_reg_submitting: 'Submitting...',
    mem_reg_success: 'Registration Submitted!',
    mem_reg_success_desc: 'Our team will contact you shortly to activate your membership.',
    mem_reg_another: 'Register Another Plan',
    admin_memberships_manage: 'Membership Registrations',
    admin_memberships_total: 'total memberships',
    admin_memberships_empty: 'No memberships registered yet.',
    admin_memberships_col_name: 'Full Name',
    admin_memberships_col_phone: 'Phone',
    admin_memberships_col_age: 'Age',
    admin_memberships_col_plan: 'Plan',
    admin_memberships_col_price: 'Price',
    admin_memberships_col_registered: 'Registered',
    admin_memberships_confirm_delete: 'Delete this membership registration?',
  },
  ar: {
    brand_name: 'جيم كوستا',
    brand_subtitle: 'بيتك الثاني',
    
    // Navbar
    nav_home: 'الرئيسية',
    nav_membership: 'الاشتراكات',
    nav_about: 'من نحن',
    nav_offers: 'العروض',
    nav_gallery: 'معرض الصور',
    nav_success: 'قصص النجاح',
    nav_contact: 'اتصل بنا',
    nav_join_now: 'اشترك الآن',

    // Hero Section
    hero_premier: 'صالة الألعاب الرياضية الرائدة في مصر',
    hero_forge_legacy: 'اصنع إرثك هنا.',
    hero_subtitle: 'أجهزة عالمية المستوى. مدربون خبراء. مجتمع يدفعك للأمام. تبدأ رحلة تغييرك في اللحظة التي تخطو فيها داخل صالتنا.',
    hero_join_now: 'اشترك الآن',
    hero_whatsapp: 'تواصل معنا',
    hero_view_offers: 'عرض العروض',
    stat_active_members: 'أعضاء نشطون',
    stat_expert_trainers: 'مدربون خبراء',
    stat_equipment_pieces: 'قطع أجهزة',
    stat_years_excellence: 'سنوات من التميز',

    // Why Choose Us
    why_accent: 'لماذا جيم كوستا؟',
    why_title: 'الفارق مع كوستا',
    why_subtitle: 'نحن لا نقدم مجرد صالة ألعاب رياضية. نحن نقدم نظاماً متكاملاً للتحول الجسدي والصحي.',
    feature_equip_title: 'أجهزة عالمية المستوى',
    feature_equip_desc: 'أكثر من 200 جهاز متميز وأوزان حرة من الشركات الرائدة عالمياً.',
    feature_trainers_title: 'مدربون خبراء',
    feature_trainers_desc: 'محترفون معتمدون مكرسون لتحولك ونجاحك الرياضي.',
    feature_programs_title: 'برامج متنوعة',
    feature_programs_desc: 'من تمارين القوة إلى الكارديو، الهيت واليوغا — لدينا كل ما تحتاجه.',
    feature_results_title: 'نتائج مثبتة',
    feature_results_desc: 'آلاف من قصص النجاح. تحولات حقيقية. أشخاص حقيقيون.',

    // Membership Section
    plans_accent: 'خطط مرنة',
    plans_title: 'خطط العضوية',
    plans_subtitle: 'بدون رسوم مخفية. بدون عقود معقدة. فقط نتائج.',
    plans_view_all: 'عرض جميع الخطط',
    plans_currency: 'ج.م',
    plans_best_value: 'أفضل قيمة',
    plans_popular: 'شائع',
    plans_month: 'شهر',
    plans_months: 'شهور',
    plans_year: 'سنة',
    plans_get_started: 'ابدأ الآن',
    plans_most_popular: 'الأكثر شعبية',
    plans_commit: 'اشترك الآن',
    plans_annual: 'الاشتراك السنوي',

    // Features Checklist
    feat_gym_access: 'وصول كامل للجيم',
    feat_locker_shower: 'استخدام الخزائن والاستحمام',
    feat_basic_assessment: 'تقييم بدني أساسي',
    feat_app_access: 'الوصول للتطبيق الخاص بالجيم',
    feat_classes_5: 'حصص جماعية (5 مرات أسبوعياً)',
    feat_classes_unlimited: 'حصص جماعية غير محدودة',
    feat_full_assessment: 'تقييم بدني شامل',
    feat_pt_1: 'جلسة تدريب شخصي واحدة شهرياً',
    feat_pt_2: 'جلستان تدريب شخصي شهرياً',
    feat_pt_4: '4 جلسات تدريب شخصي شهرياً',
    feat_nutrition_consult: 'استشارة غذائية',
    feat_nutrition_plan: 'خطة غذائية متضمنة',
    feat_nutrition_custom: 'خطة غذائية مخصصة بالكامل',
    feat_guest_2: 'بطاقات دخول للضيوف (2 شهرياً)',
    feat_guest_unlimited: 'دخول غير محدود للضيوف',
    feat_priority_booking: 'أولوية حجز الحصص',
    feat_priority_all: 'أولوية في كل شيء',
    feat_assigned_locker: 'خزانة ملابس خاصة ومخصصة',
    feat_quarterly_assessment: 'تقييمات بدنية ربع سنوية',
    feat_merchandise: 'ملابس وأدوات مجانية من جيم كوستا',

    // Testimonials
    test_accent: 'نتائج حقيقية',
    test_title: 'قصص الأعضاء',
    test_subtitle: 'استمع إلى الأشخاص الذين غيروا حياتهم مع جيم كوستا.',
    test_more: 'المزيد من قصص النجاح',
    test_name_ahmed: 'أحمد حسن',
    test_role_ahmed: 'خسر 30 كجم في 6 أشهر',
    test_text_ahmed: 'جيم كوستا غير حياتي تمامًا. المدربون هنا يدفعونك لتكون أفضل نسخة من نفسك.',
    test_name_sara: 'سارة محمد',
    test_role_sara: 'شاركت في بطولات وطنية',
    test_text_sara: 'انتقلت من عدم ممارسة رفع الأثقال مطلقًا إلى المشاركة في البطولات الوطنية. التدريب هنا لا مثيل له.',
    test_name_khaled: 'خالد إبراهيم',
    test_role_khaled: 'كسب 15 كجم من العضلات',
    test_text_khaled: 'البرامج والنصائح الغذائية والمجتمع هنا لا مثيل له في مصر.',

    // CTA Banner
    cta_ready: 'جاهز للبدء؟',
    cta_start: 'ابدأ تحولك الجسدي اليوم',
    cta_subtitle: 'أهدافك في انتظارك. أفضل نسخة منك في انتظارك. توقف عن الانتظار وابدأ الآن.',
    cta_join: 'اشترك الآن',
    cta_contact: 'اتصل بنا',

    // Footer
    footer_desc: 'بيتك الثاني. تجربة لياقة بدنية متميزة في مصر. غير جسدك، تغلّب على حدودك، وتفوّق في حياتك.',
    footer_quick_links: 'روابط سريعة',
    footer_contact: 'اتصل بنا',
    footer_hours: 'ساعات العمل',
    footer_open_365: 'مفتوح 365 يوماً في السنة',
    footer_admin: 'لوحة التحكم للمشرفين',
    footer_copyright: 'جيم كوستا. جميع الحقوق محفوظة.',

    // Membership Page
    mem_accent: 'خيارات مرنة',
    mem_title: 'خطط العضوية',
    mem_subtitle: 'اختر الخطة التي تناسب أهدافك. تشمل كل خطة وصولاً كاملاً إلى مرافقنا ذات المستوى العالمي.',
    mem_include_title: 'جميع الخطط تشمل',
    mem_inc_1: 'وصول مجاني للخزائن والاستحمام',
    mem_inc_2: 'مواقف سيارات مجانية للأعضاء',
    mem_inc_3: 'صالة رياضية مكيفة بالكامل',
    mem_inc_4: 'أجهزة رياضية معقمة يومياً',
    mem_inc_5: 'إنترنت واي فاي سريع في جميع أنحاء الجيم',
    mem_inc_6: 'غرف تبديل ملابس مخصصة ونظيفة',
    mem_inc_7: 'بدون رسوم تسجيل إضافية للاشتراكات السنوية',
    mem_inc_8: 'إمكانية الإلغاء في أي وقت (تطبق الشروط والأحكام)',

    // About Page
    ab_accent: 'قصتنا',
    ab_title: 'عن جيم كوستا',
    ab_est: 'تأسس عام 2014',
    ab_story_title: 'قصتنا',
    ab_story_p1: 'ولد جيم كوستا من إيمان بسيط وقوي: يستحق كل شخص الوصول إلى مستوى تدريبي عالمي. تأسس في عام 2014 من قبل الرياضي الوطني السابق أحمد السيد، وبدأ كوستا كصالة بمساحة 500 متر مربع تخدم 30 عضواً فقط.',
    ab_story_p2: 'اليوم، ندير صالة رياضية متطورة بمساحة 3,000 متر مربع، ونخدم أكثر من 5,000 عضو نشط، وساعدنا الآلاف على تحقيق تحولات اعتقدوا يوماً أنها مستحيلة.',
    ab_story_p3: 'فلسفتنا بسيطة: التميز في كل شيء. من أجهزتنا إلى كفاءة مدربينا، ومن توجيهات التغذية لدينا إلى ثقافة مجتمعنا — لا نرضى بأي شيء أقل من الأفضل.',
    ab_years_operating: 'سنوات العمل',
    ab_active_members: 'الأعضاء النشطون',
    ab_certified_trainers: 'المدربون المعتمدون',
    ab_equipment_pieces: 'قطع الأجهزة الرياضية',
    ab_sqm_facility: 'مساحة المنشأة (متر مربع)',
    ab_weekly_classes: 'حصص أسبوعية جماعية',
    ab_facilities_accent: 'مستوى عالمي',
    ab_facilities_title: 'مرافقنا الرياضية',
    ab_facilities_subtitle: 'كل ما تحتاجه للتدريب والاستشفاء والتميز البدني.',
    ab_facility_weights: 'منطقة الأوزان الحرة',
    ab_facility_weights_desc: 'دمبلز تصل إلى 100 كجم، بارات أولمبية، ومنطقة كاملة لأجهزة القرفصاء والرفعات الحرة.',
    ab_facility_cardio: 'منطقة الكارديو واللياقة',
    ab_facility_cardio_desc: 'أجهزة المشي، الدراجات، أجهزة التجديف وصعود الدرج — جميعها من ماركات رائدة.',
    ab_facility_classes: 'استوديو التمارين الجماعية',
    ab_facility_classes_desc: 'حصص HIIT، سبينينغ، زومبا، وبيلاتس — أكثر من 30 حصة أسبوعية متنوعة.',
    ab_facility_func: 'تمارين الكروسفيت والتدريب الوظيفي',
    ab_facility_func_desc: 'أجهزة الحبال، تمارين TRX، حبال القوة، زلاجة الأوزان والمزيد من أدوات اللياقة البدنية.',
    ab_facility_lockers: 'غرف تبديل ملابس متميزة',
    ab_facility_lockers_desc: 'غرف واسعة، نظيفة ومجهزة بخزائن آمنة واستحمام بالماء الساخن.',
    ab_facility_parking: 'مواقف سيارات مجانية للأعضاء',
    ab_facility_parking_desc: 'مواقف خاصة ومؤمنة مخصصة لسيارات المشتركين متوفرة طوال الوقت.',
    ab_facility_wifi: 'واي فاي عالي السرعة',
    ab_facility_wifi_desc: 'اتصال إنترنت سريع متاح مجاناً في كافة أرجاء الصالة الرياضية.',
    ab_facility_recovery: 'منطقة الاستشفاء والاسترخاء',
    ab_facility_recovery_desc: 'حمامات ثلج، غرف ساونا، وخدمات العلاج الطبيعي والمساج الرياضي المتكامل.',
    ab_team_accent: 'فريق العمل',
    ab_trainers_title: 'تعرف على مدربينا',
    ab_trainers_subtitle: 'خبراء معتمدون دولياً يعيشون ويتنفسون اللياقة البدنية.',
    ab_trainer_mustafa: 'الكوتش مصطفى',
    ab_trainer_mustafa_spec: 'القوة البدنية ورفع الأثقال',
    ab_trainer_rana: 'الكوتش رنا',
    ab_trainer_rana_spec: 'خسارة الوزن ونحت القوام',
    ab_trainer_tarek: 'الكوتش طارق',
    ab_trainer_tarek_spec: 'التحضير الرياضي للألعاب المختلفة',
    ab_trainer_nadia: 'الكوتش نادية',
    ab_trainer_nadia_spec: 'اليوغا، المرونة والاسترخاء',
    ab_experience: 'خبرة',
    ab_years: 'سنوات',

    // Contact Page
    con_accent: 'ابق على اتصال',
    con_title: 'تواصل معنا',
    con_name_label: 'الاسم بالكامل *',
    con_email_label: 'البريد الإلكتروني *',
    con_phone_label: 'رقم الهاتف *',
    con_message_label: 'رسالتك *',
    con_name_place: 'اكتب اسمك الكامل هنا',
    con_email_place: 'اكتب بريدك الإلكتروني هنا',
    con_phone_place: 'رقم هاتفك (مثال: +201XXXXXXXX)',
    con_message_place: 'كيف يمكننا مساعدتك؟ اكتب استفسارك هنا.',
    con_send: 'إرسال الرسالة',
    con_sending: 'جاري الإرسال...',
    con_info_title: 'معلومات الاتصال',
    con_info_desc: 'هل لديك استفسارات؟ نسعد بالإجابة عليها. زرنا في مقرنا أو تواصل معنا عبر الرسائل.',
    con_location_title: 'الموقع والجغرافيا',
    con_hours_title: 'مواعيد العمل الرسمية',
    con_follow_title: 'تابعنا عبر منصاتنا',

    // Offers Page
    off_accent: 'عروض حصرية',
    off_title: 'العروض الحالية والنشطة',
    off_subtitle: 'استغل الفرصة مع عروضنا الترويجية لفترة محدودة وابدأ مشوار لياقتك اليوم.',
    off_claim: 'الحصول على العرض',
    off_expired: 'منتهي الصلاحية',
    off_ends: 'ينتهي في',
    off_comp_title: 'المسابقات والفعاليات الجارية',
    off_comp_subtitle: 'تحدّى نفسك، نافس الآخرين واربح جوائز قيمة ورائعة من جيم كوستا.',
    off_comp_join: 'الاشتراك في المسابقة',
    off_comp_joined: 'تم الاشتراك بالفعل',
    off_comp_ends: 'تنتهي خلال',
    off_comp_prize: 'الجائزة الكبرى',

    // Success Stories Page
    succ_accent: 'قصص التحول البدني',
    succ_title: 'قصص نجاح أعضائنا',
    succ_subtitle: 'أعضاء حقيقيون. التزام حقيقي. نتائج مذهلة غيرت حياتهم للأفضل.',
    succ_before: 'قبل',
    succ_after: 'بعد',
    succ_lost: 'خسر',
    succ_gained: 'اكتسب',
    succ_in: 'خلال',
    succ_months: 'أشهر',
    succ_read_more: 'قراءة تفاصيل القصة',

    // Gallery Page
    gal_accent: 'جولة داخل كوستا',
    gal_title: 'معرض الصور',
    gal_subtitle: 'شاهد لقطات ومرافق وصالة الألعاب الرياضية الفاخرة والأجهزة المتوفرة لدينا.',
    gal_all: 'الكل',
    gal_weights: 'منطقة الحديد',
    gal_cardio: 'منطقة الكارديو',
    gal_studio: 'الاستوديوهات الحصص',
    gal_recovery: 'الاستشفاء والساونا',

    // Admin Sidebar Layout
    admin_title: 'لوحة التحكم للمشرفين',
    admin_nav_dashboard: 'لوحة التحكم',
    admin_nav_offers: 'العروض',
    admin_nav_competitions: 'المسابقات',
    admin_nav_entries: 'مشاركات المسابقات',
    admin_nav_trials: 'فترات تجريبية',
    admin_nav_memberships: 'اشتراكات العضوية',
    admin_logout: 'تسجيل الخروج',
    admin_panel_subtitle: 'بوابة المشرفين',

    // Admin Login Page
    admin_login_title: 'تسجيل دخول المشرف',
    admin_login_email: 'البريد الإلكتروني',
    admin_login_password: 'كلمة المرور',
    admin_login_button: 'تسجيل الدخول',
    admin_login_signing_in: 'جاري الدخول...',
    admin_login_unauthorized: 'منطقة محمية. يمنع الدخول لغير المصرح لهم.',

    // DataTable
    admin_table_search: 'بحث...',
    admin_table_export: 'تصدير كـ CSV',
    admin_table_loading: 'جاري تحميل السجلات...',
    admin_table_action: 'الإجراء',
    admin_table_showing: 'عرض',
    admin_table_of: 'من',
    admin_table_records: 'سجلات',

    // Admin Dashboard
    admin_db_overview: 'نظرة عامة على نشاط صالتك الرياضية',
    admin_db_recent_trials: 'التسجيلات التجريبية الأخيرة',
    admin_db_recent_entries: 'مشاركات المسابقة الأخيرة',
    admin_db_recent_memberships: 'اشتراكات العضوية الأخيرة',
    admin_db_view_all: 'عرض الكل',
    admin_db_no_reg: 'لا توجد تسجيلات بعد.',
    admin_db_no_entries: 'لا توجد مشاركات مسابقات بعد.',
    admin_db_no_memberships: 'لا توجد اشتراكات عضوية بعد.',

    // Admin Offers
    admin_offers_manage: 'إدارة العروض',
    admin_offers_total: 'إجمالي العروض',
    admin_offers_new: 'عرض جديد',
    admin_offers_no: 'لا توجد عروض بعد. أنشئ عرضك الأول!',
    admin_offers_col_title: 'العنوان',
    admin_offers_col_desc: 'الوصف',
    admin_offers_col_end: 'تاريخ الانتهاء',
    admin_offers_col_status: 'الحالة',
    admin_offers_active: 'نشط',
    admin_offers_off: 'مغلق',
    admin_offers_edit: 'تعديل العرض',
    admin_offers_create: 'إنشاء عرض جديد',
    admin_offers_form_title: 'العنوان *',
    admin_offers_form_desc: 'الوصف *',
    admin_offers_form_end: 'تاريخ الانتهاء',
    admin_offers_form_active: 'نشط (يظهر في الموقع)',
    admin_offers_save: 'إنشاء العرض',
    admin_offers_update: 'تحديث العرض',
    admin_offers_saving: 'جاري الحفظ...',
    admin_offers_cancel: 'إلغاء',
    admin_offers_confirm_delete: 'هل تريد حذف هذا العرض؟',

    // Admin Competitions
    admin_comps_manage: 'إدارة المسابقات',
    admin_comps_total: 'إجمالي المسابقات',
    admin_comps_new: 'مسابقة جديدة',
    admin_comps_no: 'لا توجد مسابقات بعد.',
    admin_comps_prize: 'الجائزة',
    admin_comps_ends: 'ينتهي في',
    admin_comps_pick_winner: 'اختيار الفائز',
    admin_comps_edit: 'تعديل المسابقة',
    admin_comps_create: 'إنشاء مسابقة',
    admin_comps_form_title: 'العنوان *',
    admin_comps_form_desc: 'الوصف *',
    admin_comps_form_prize: 'الجائزة *',
    admin_comps_form_end: 'تاريخ الانتهاء',
    admin_comps_form_active: 'نشط (يظهر في الموقع)',
    admin_comps_save: 'إنشاء',
    admin_comps_update: 'تحديث',
    admin_comps_confirm_delete: 'هل تريد حذف هذه المسابقة وجميع مشاركاتها؟',
    admin_comps_winner_title: 'مولد الفائز العشوائي',
    admin_comps_winner_pick: 'اختيار فائز عشوائي',
    admin_comps_winner_selecting: 'جاري اختيار الفائز...',
    admin_comps_winner_text: 'انقر فوق الزر لتحديد فائز عشوائيًا من بين جميع المشاركين المسجلين.',
    admin_comps_winner_success: 'تم اختيار الفائز!',
    admin_comps_winner_saved: 'تم حفظ الفائز في قاعدة البيانات ✓',
    admin_comps_winner_no_entries: 'لا توجد مشاركات في هذه المسابقة.',
    admin_comps_winner_close: 'إغلاق',

    // Admin Trial Registrations
    admin_trials_manage: 'تسجيلات الفترة التجريبية',
    admin_trials_total: 'إجمالي التسجيلات',
    admin_trials_empty: 'لا توجد تسجيلات تجريبية بعد.',
    admin_trials_col_name: 'الاسم بالكامل',
    admin_trials_col_phone: 'رقم الهاتف',
    admin_trials_col_age: 'العمر',
    admin_trials_col_goal: 'الهدف',
    admin_trials_col_registered: 'تاريخ التسجيل',
    admin_trials_confirm_delete: 'هل تريد حذف هذا التسجيل؟',

    // Admin Competition Entries
    admin_entries_manage: 'مشاركات المسابقة',
    admin_entries_total: 'إجمالي المشاركات',
    admin_entries_empty: 'لا توجد مشاركات مسابقات بعد.',
    admin_entries_col_name: 'الاسم بالكامل',
    admin_entries_col_phone: 'رقم الهاتف',
    admin_entries_col_comp: 'المسابقة',
    admin_entries_col_registered: 'تاريخ الاشتراك',
    admin_entries_confirm_delete: 'هل تريد حذف هذه المشاركة من المسابقة؟',

    // Membership Registration Form & Admin Membership
    mem_reg_title: 'اشتراك العضوية',
    mem_reg_subtitle: 'سجل بياناتك للاشتراك في الباقة المختارة',
    mem_reg_plan: 'الباقة المختارة',
    mem_reg_price: 'السعر',
    mem_reg_submit: 'اشترك الآن',
    mem_reg_submitting: 'جاري التسجيل...',
    mem_reg_success: 'تم إرسال طلب الاشتراك بنجاح!',
    mem_reg_success_desc: 'سيتواصل معك فريقنا قريباً لتفعيل اشتراكك.',
    mem_reg_another: 'الاشتراك في باقة أخرى',
    admin_memberships_manage: 'اشتراكات العضوية',
    admin_memberships_total: 'إجمالي الاشتراكات',
    admin_memberships_empty: 'لا توجد اشتراكات عضوية بعد.',
    admin_memberships_col_name: 'الاسم بالكامل',
    admin_memberships_col_phone: 'رقم الهاتف',
    admin_memberships_col_age: 'العمر',
    admin_memberships_col_plan: 'الباقة',
    admin_memberships_col_price: 'السعر',
    admin_memberships_col_registered: 'تاريخ الاشتراك',
    admin_memberships_confirm_delete: 'هل تريد حذف هذا الاشتراك؟',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    // Set HTML lang and dir attribute automatically
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
